using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using Common;
using GD_NHANVIEN.DAL;
namespace GD_NHANVIEN.GUI
{
    public partial class ChiTietHDTC : DevExpress.XtraEditors.XtraForm
    {
        HoaDonTC f;
        public string idsim1 = "";
        public string idkh = "";
        public ChiTietHDTC(HoaDonTC ff, string idsim, string idmakh)
        {
            InitializeComponent();
            HoaDonTCDAL dal = new HoaDonTCDAL();
            txtidsim.Text = dal.GetPrintSim(Convert.ToInt32(idsim));
            txtmakh.Text = dal.GetPrintMaKH(Convert.ToInt32(idmakh));
            txtnam.Text = DateTime.Now.Year.ToString();
            idsim1 = idsim;
            idkh = idmakh;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.ChitietHDTCs.Load();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            f = ff;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            if(cbbthang.Text=="")
                MessageBox.Show("Vui lòng chọn tháng SIM sử dụng!!", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            else
            {
                ChiTietHDTCDAL dal = new ChiTietHDTCDAL();
                var result = dal.Load(Convert.ToInt32(idsim1), Convert.ToInt32(cbbthang.Text), Convert.ToInt32(idkh));
                chitietHDTCsBindingSource.DataSource = result;
            }
            
        }

        private void txtnam_TextChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            ChiTietHDTCDAL dal = new ChiTietHDTCDAL();
            var result = dal.TinhTien(Convert.ToInt32(idsim1), Convert.ToInt32(cbbthang.Text), Convert.ToInt32(idkh));
            txtthanhtien.Text = result.ToString();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            f.Thanhtien = txtthanhtien.Text;
            f.Tongtien = (Convert.ToInt32(txtthanhtien.Text) + 50000).ToString();
            f.Change3();
            f.Change4();
            this.Close();

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}