using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace GD_NHANVIEN.GUI
{
    public partial class HoaDonTC : DevExpress.XtraEditors.XtraForm
    {
        public HoaDonTC()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.HoaDonTinhCuocs.Load();
            //// This line of code is generated by Data Source Configuration Wizard
            //hoaDonTinhCuocsBindingSource.DataSource = dbContext.HoaDonTinhCuocs.Local.ToBindingList();
        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
            //ThongtinKH f = new ThongtinKH();
            //f.Show();
        }

        private void simpleButton7_Click(object sender, EventArgs e)
        {
            ThongtinSIM f = new ThongtinSIM();
            f.Show();
        }
    }
}